server:
  port: 8081
spring:
  application:
    name: search-service

  datasource:
    url: jdbc:postgresql://localhost:5432/vendor_search
    username: postgres
    password: root

search-framework:

  entities:

    vendor:

      table-name: vendor_search

      search-fields:
        - vendor_name
        - company_name
        - vendor_number

      sortable-fields:
        - vendor_name
        - vendor_number
        - company_name

      filterable-fields:
        - department
        - supplier_status
        - company_name
        - location_id

      search:

        mode: FULL_TEXT

        capabilities:
          fuzzy: true

        fuzzy-threshold: 0.2

      autocomplete:

        enabled: true

        fields:
          - vendor_name
          - company_name
          - vendor_number

        fuzzy-excluded-fields:
          - vendor_number

        capabilities:
          prefix: true
          fuzzy: true

        fuzzy-threshold: 0.2

      features:
        ranking: false
        pagination: true